/* FILE: generateInput.h
 * AUTHOR: Cameron Petkov
 * UNIT: Unix and C Programming
 * PURPOSE: General header includes, definitions, and forward-declarations.
 * REFERENCE: Data pool from randomlists.com's TV and movie show generator:
 *            (randomlists.com, n.d.)
 * LAST MOD: 27/05/2018
 * COMMENTS: None
 */


#ifndef GENERATEINPUT_H
#define GENERATEINPUT_H



#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>

#include "boolean.h"


/* 397 entries in total */
#define ARRAY_LENGTH 397


    /* Data pool from randomlists.com's TV and movie show generator 
     * (randomlists.com, n.d.) */
    char *entryPool[ARRAY_LENGTH] = 
    {
"Sin City: A Dame to Kill For",
"Avatar",
"The Hunger Games: Mockingjay - Part 1",
"The Commuter",
"Cinderella",
"Anon",
"Mission: Impossible - Rogue Nation",
"Dracula Untold",
"Gravity",
"Dawn of the Planet of the Apes",
"Furious 7",
"Star Wars: The Last Jedi",
"The Lord of the Rings: The Fellowship of the Ring",
"2001: A Space Odyssey",
"Three Billboards Outside Ebbing, Missouri",
"Horrible Bosses 2",
"The Incredible Hulk",
"Jurassic World",
"Murder on the Orient Express",
"Blade Runner",
"Valerian and the City of a Thousand Planets",
"Den of Thieves",
"Red Sparrow",
"Ice Age: Continental Drift",
"Blockers",
"Spirited Away",
"Coco",
"Solo: A Star Wars Story",
"Beauty and the Beast",
"Finding Nemo",
"Spectre",
"The Titan",
"Chappie",
"Maze Runner: The Scorch Trials",
"Pirates of the Caribbean: Dead Men Tell No Tales",
"The Lion King",
"Inception",
"The Maze Runner",
"Iron Man 2",
"Deadpool",
"Justice League",
"The Godfather",
"John Wick: Chapter 2",
"Mission: Impossible",
"Sherlock Holmes: A Game of Shadows",
"Man of Steel",
"Frozen",
"How to Train Your Dragon 2",
"Sleight",
"Thor: The Dark World",
"Snowpiercer",
"Django Unchained",
"John Wick",
"The Equalizer",
"Avengers: Age of Ultron",
"Star Wars",
"Maze Runner: The Death Cure",
"Gladiator",
"Pirates of the Caribbean: Dead Man's Chest",
"Inside Out",
"Jurassic World: Fallen Kingdom",
"Pirates of the Caribbean: At World's End",
"Dirty Dead Con Men",
"A Quiet Place",
"Ant-Man",
"Twelve Monkeys",
"X-Men: Apocalypse",
"Birdman",
"Alien",
"The Judge",
"The Wolf of Wall Street",
"Deadpool 2",
"Batman v Superman: Dawn of Justice",
"Men in Black",
"Thor: Ragnarok",
"Taken 3",
"Prometheus",
"Pirates of the Caribbean: The Curse of the Black Pearl",
"X-Men: Days of Future Past",
"Zootopia",
"The Imitation Game",
"Rampage",
"Rise of the Planet of the Apes",
"The Purge",
"Fight Club",
"Mission: Impossible - Ghost Protocol",
"The Lord of the Rings: The Return of the King",
"Baby Driver",
"Meet Me In St. Gallen",
"Gone Girl",
"Insurgent",
"Pacific Rim",
"What the Waters Left Behind",
"The Amazing Spider-Man",
"It Follows",
"Casino Royale",
"Kong: Skull Island",
"Mad Max: Fury Road",
"Star Wars: The Force Awakens",
"Saving Private Ryan",
"Captain America: The Winter Soldier",
"Toy Story",
"Fifty Shades Freed",
"Kingsman: The Golden Circle",
"The Twilight Saga: Breaking Dawn - Part 2",
"Captain America: The First Avenger",
"The Dark Knight Rises",
"Raiders of the Lost Ark",
"The Shining",
"Despicable Me 2",
"Jumanji: Welcome to the Jungle",
"Guardians of the Galaxy",
"Teenage Mutant Ninja Turtles",
"Iron Man",
"Harry Potter and the Deathly Hallows: Part 2",
"Doctor Strange",
"Hacksaw Ridge",
"Saw",
"Ice Age",
"Fantastic Beasts and Where to Find Them",
"Skyfall",
"The Fifth Element",
"Salt",
"The 15:17 to Paris",
"Maleficent",
"Kamen Rider Heisei Generations FINAL: Build & Ex-Aid with Legend Riders",
"Pirates of the Caribbean: On Stranger Tides",
"Despicable Me",
"Ex Machina",
"La La Land",
"Toy Story 2",
"Geostorm",
"Fantastic Four",
"The Grand Budapest Hotel",
"Spider-Man: Homecoming",
"The Jungle Book",
"Ghost in the Shell",
"Pulp Fiction",
"Ice Age: The Meltdown",
"Beauty and the Beast",
"Game Night",
"Iron Man 3",
"Ready Player One",
"Wonder Woman",
"American Pie",
"Monsters, Inc.",
"Terminator 2: Judgment Day",
"Big Hero 6",
"The Shape of Water",
"One Flew Over the Cuckoo's Nest",
"Divergent",
"The Avengers",
"Fifty Shades of Grey",
"Transformers: Age of Extinction",
"Blade Runner 2049",
"Fifty Shades Darker",
"Twilight",
"The Mummy: Tomb of the Dragon Emperor",
"Psycho",
"The Dark Tower",
"Logan",
"Harry Potter and the Philosopher's Stone",
"The Lord of the Rings: The Two Towers",
"Apollo 13",
"Wreck-It Ralph",
"Thor",
"Captain America: Civil War",
"I, Robot",
"Nightcrawler",
"Men in Black II",
"Jupiter Ascending",
"Interstellar",
"Tomb Raider",
"Dunkirk",
"San Andreas",
"Untitled Avengers Movie",
"Black Panther",
"Miss Peregrine's Home for Peculiar Children",
"The Terminator",
"Hercules",
"Se7en",
"Terminator Genisys",
"Tomorrowland",
"Batman Begins",
"Guardians of the Galaxy Vol. 2",
"Southpaw",
"Fury",
"Up",
"The Hobbit: The Battle of the Five Armies",
"Split",
"Leon: The Professional",
"Back to the Future",
"War for the Planet of the Apes",
"Darkest Hour",
"The Hitman's Bodyguard",
"Pitch Perfect 3",
"Inglourious Basterds",
"Avengers: Infinity War",
"Ice Age: Dawn of the Dinosaurs",
"NCIS: Los Angeles",
"The King of Queens",
"Chicago Med",
"Game of Thrones",
"Siren",
"Person of Interest",
"Bones",
"New Girl",
"Gotham",
"Alias",
"The Magicians",
"The X-Files",
"My Little Pony: Friendship Is Magic",
"MythBusters",
"Sleepy Hollow",
"24",
"Sons of Anarchy",
"The Good Wife",
"Dragon Ball Super",
"Breaking Bad",
"Two and a Half Men",
"Lucifer",
"Community",
"Baywatch",
"Timeless",
"The Young and the Restless",
"Star Wars: The Clone Wars",
"Dragon Ball Z",
"Casualty",
"The Fosters",
"The 100",
"PBS NewsHour",
"Friends",
"Late Show with David Letterman",
"WWE Raw",
"Suits",
"The Mentalist",
"The Colbert Report",
"Grey's Anatomy",
"Twin Peaks",
"How to Get Away with Murder",
"The Flash",
"NOVA",
"Marvel's Daredevil",
"Quantico",
"Chicago Fire",
"Riverdale",
"Smallville",
"Star Trek",
"Shadowhunters",
"Seinfeld",
"Paw Patrol",
"Polizeiruf 110",
"Infinite Challenge",
"S.W.A.T.",
"Doctor Who",
"South Park",
"The Last Man on Earth",
"House",
"Mr. Robot",
"iZombie",
"Firefly",
"Castle",
"Once Upon a Time",
"Blue Bloods",
"Star Trek: The Next Generation",
"Law & Order: Special Victims Unit",
"Shameless",
"Stranger Things",
"black-ish",
"The Blacklist",
"Star Wars Rebels",
"CSI: Crime Scene Investigation",
"American Dad!",
"Power Couple Brasil",
"Lethal Weapon",
"The Big Bang Theory",
"Vikings",
"Taarak Mehta Ka Ooltah Chashmah",
"American Horror Story",
"Spartacus",
"Prison Break",
"Black Mirror",
"Agatha Christie's Poirot",
"The Voice",
"Californication",
"The Fairly OddParents",
"The Lord of the Skies",
"Hannibal",
"Sesame Street",
"Chicago P.D.",
"Money Heist",
"Steven Universe",
"American Idol",
"True Detective",
"The Handmaid's Tale",
"Fargo",
"Criminal Minds",
"America's Funniest Home Videos",
"Cobra Kai",
"Outlander",
"Lost",
"Dark Shadows",
"NCIS",
"Sex and the City",
"Supernatural",
"Family Guy",
"Narcos",
"Orange Is the New Black",
"Celebrity Big Brother",
"The Americans",
"How I Met Your Mother",
"DC's Legends of Tomorrow",
"Marvel's Jessica Jones",
"Pretty Little Liars",
"NCIS: New Orleans",
"The Office",
"The Missing",
"It's Always Sunny in Philadelphia",
"Westworld",
"Ancient Aliens",
"VICE",
"My Hero Academia",
"Ash vs Evil Dead",
"The Sopranos",
"Gunsmoke",
"Fringe",
"Doctor Who",
"Coronation Street",
"Black Sails",
"Designated Survivor",
"Legion",
"Blindspot",
"Archer",
"Futurama",
"Modern Family",
"Mindhunter",
"Fear the Walking Dead",
"Boruto: Naruto Next Generations",
"Empire",
"Mysterious Personal Shopper",
"Mom",
"Grimm",
"Marvel's Iron Fist",
"The Middle",
"Stargate SG-1",
"Colony",
"Real Time with Bill Maher",
"The Expanse",
"Elementary",
"Homeland",
"Adventure Time",
"Law & Order",
"Super Sentai",
"Silicon Valley",
"The Bold and the Beautiful",
"The Walking Dead",
"The Vampire Diaries",
"Teen Wolf",
"True Blood",
"Billions",
"Hawaii Five-0",
"Young Sheldon",
"General Hospital",
"EastEnders",
"Scorpion",
"The Graham Norton Show",
"Into the Badlands",
"Marvel's Agents of S.H.I.E.L.D.",
"State of Affairs",
"Bull",
"Sherlock",
"The Simpsons",
"The Rain",
"Arrow",
"Arrested Development",
"The Goldbergs",
"Last Week Tonight with John Oliver",
"The Originals",
"13 Reasons Why",
"Scandal",
"Z Nation",
"House of Cards",
"Emmerdale",
"One Piece",
"Better Call Saul",
"Supergirl",
"Top Gear",
"Atlanta",
"The Wire",
"Rick and Morty",
"Dexter",
"The Daily Show with Trevor Noah",
"Brooklyn Nine-Nine",
"The Tonight Show Starring Jimmy Fallon",
"Scrubs",
"Survivor",
"Heroes"
    };


char* dayFind( int dayID );
int writeInputFile( char *entryPool[], FILE *f, char argv[] );



#endif
